#!/usr/bin/env python3
"""Merge one lab's gap list into the shared work queue at docs/labs/TODO.md.

Evaluating labs one at a time would clobber a single shared file, so the merge
is scripted rather than hand-edited: each lab owns a section keyed by its
filename, sections are re-sorted worst-score-first so the queue reads as a work
order, and the summary table at the top is rebuilt from per-section metadata
comments. Items a human has already ticked off stay ticked when the lab is
re-evaluated, so the file is safe to work from between runs.

Usage:
    python3 update_todo.py docs/labs/10-led-circuit.md \
        --score 7 --band Stub --gaps /tmp/gaps.md

    python3 update_todo.py docs/labs/10-led-circuit.md --clear
    python3 update_todo.py --list

The --gaps file is a markdown checkbox list you write, for example:

    - [ ] **Build procedure** (+14) — no numbered steps at all; a student has
      no path from parts to a lit LED.
      - How: write directly, following references/lab-template.md
    - [ ] **MicroSim with current animation** (+12) — links to two sims but
      embeds neither.
      - How: `breadboard-sim-generator`
"""

import argparse
import datetime
import os
import re
import sys

HEADER = """# Hands-On Lab TODO

Work queue generated by the `hands-on-lab-evaluator` skill. Each section lists
the content gaps found in one lab, ordered by how many rubric points they are
worth. Labs are listed worst-score-first, so the top of this file is where the
next hour of work should go.

Tick an item off when it is done — re-running the evaluator preserves your
checkmarks. When a lab has no gaps left, its section is removed automatically.

This page is excluded from the built site via `exclude_docs` in `mkdocs.yml`;
it is a work file for authors, not a page for students.
"""

META_RE = re.compile(
    r"<!--\s*lab:\s*(?P<lab>[^|]+?)\s*\|\s*score:\s*(?P<score>\d+)\s*\|"
    r"\s*band:\s*(?P<band>[^|]+?)\s*\|\s*updated:\s*(?P<updated>[^|]+?)\s*\|"
    r"\s*top:\s*(?P<top>.*?)\s*-->")


def find_project_root(start):
    d = os.path.abspath(start)
    while d != os.path.dirname(d):
        if os.path.isfile(os.path.join(d, "mkdocs.yml")):
            return d
        d = os.path.dirname(d)
    raise SystemExit("ERROR: could not find mkdocs.yml above " + start)


def lab_key(lab_path):
    """Identify a lab by the path a reader would click, relative to docs/labs."""
    lab_path = os.path.abspath(lab_path)
    if os.path.isdir(lab_path):
        return os.path.basename(lab_path) + "/index.md"
    if os.path.basename(lab_path) == "index.md":
        return os.path.basename(os.path.dirname(lab_path)) + "/index.md"
    return os.path.basename(lab_path)


def lab_title(lab_path):
    """Prefer the frontmatter title, fall back to the H1, then the filename."""
    path = os.path.join(lab_path, "index.md") if os.path.isdir(lab_path) else lab_path
    if not os.path.isfile(path):
        return os.path.splitext(os.path.basename(path))[0]
    with open(path, encoding="utf-8") as f:
        text = f.read()
    fm = re.match(r"\A---\r?\n(.*?)\r?\n---", text, re.DOTALL)
    if fm:
        m = re.search(r"^title\s*:\s*(.+)$", fm.group(1), re.MULTILINE)
        if m:
            return m.group(1).strip().strip('"').strip("'")
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return os.path.splitext(os.path.basename(path))[0]


# --------------------------------------------------------------------------
# Parsing an existing TODO.md into sections
# --------------------------------------------------------------------------


def parse_todo(todo_path):
    """Return a list of {lab, score, band, updated, top, body} in file order."""
    if not os.path.isfile(todo_path):
        return []
    with open(todo_path, encoding="utf-8") as f:
        text = f.read()
    sections = []
    parts = re.split(r"^##\s+", text, flags=re.MULTILINE)[1:]
    for part in parts:
        meta = META_RE.search(part)
        if not meta:
            continue  # a hand-written section without metadata; leave it alone
        body = META_RE.sub("", part)
        body = body.split("\n", 1)[1] if "\n" in body else ""
        sections.append({
            "lab": meta.group("lab"),
            "score": int(meta.group("score")),
            "band": meta.group("band"),
            "updated": meta.group("updated"),
            "top": meta.group("top"),
            "body": body.strip("\n"),
        })
    return sections


def completed_labels(body):
    """Bold labels of items already ticked off, so a re-run does not undo them."""
    done = set()
    for line in body.splitlines():
        m = re.match(r"^\s*-\s*\[[xX]\]\s*\*\*(.+?)\*\*", line)
        if m:
            done.add(m.group(1).strip().lower())
    return done


def reapply_completed(new_body, done):
    out = []
    for line in new_body.splitlines():
        m = re.match(r"^(\s*-\s*)\[[ xX]\](\s*\*\*(.+?)\*\*)", line)
        if m and m.group(3).strip().lower() in done:
            line = f"{m.group(1)}[x]{m.group(2)}" + line[m.end():]
        out.append(line)
    return "\n".join(out)


def open_items(body):
    return len(re.findall(r"^\s*-\s*\[ \]", body, re.MULTILINE))


def first_gap_label(body):
    m = re.search(r"^\s*-\s*\[ \]\s*\*\*(.+?)\*\*", body, re.MULTILINE)
    return m.group(1).strip() if m else "see section"


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def render(sections):
    sections = sorted(sections, key=lambda s: (s["score"], s["lab"]))
    lines = [HEADER, "", "| Lab | Score | Band | Open items | Biggest gap | Updated |",
             "|------|-------|------|-----------|-------------|---------|"]
    for s in sections:
        lines.append(
            f"| [{s['title']}]({s['lab']}) | {s['score']}/100 | {s['band']} | "
            f"{open_items(s['body'])} | {s['top']} | {s['updated']} |")
    if not sections:
        lines.append("| _no open gaps_ | | | | | |")
    lines.append("")
    for s in sections:
        lines.append(f"## {s['title']} — `{s['lab']}` ({s['score']}/100)")
        lines.append("")
        lines.append(f"<!-- lab: {s['lab']} | score: {s['score']} | band: {s['band']} "
                     f"| updated: {s['updated']} | top: {s['top']} -->")
        lines.append("")
        lines.append(s["body"].strip("\n"))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description="Merge a lab's gaps into docs/labs/TODO.md")
    ap.add_argument("lab", nargs="?", help="path to the lab .md file or directory")
    ap.add_argument("--score", type=int, help="rubric score 0-100")
    ap.add_argument("--band", help="band name, e.g. Stub / Draft / Classroom-ready")
    ap.add_argument("--gaps", help="path to a markdown checkbox list of gaps")
    ap.add_argument("--top-gap", help="override the biggest-gap summary text")
    ap.add_argument("--title", help="override the lab title")
    ap.add_argument("--clear", action="store_true",
                    help="remove this lab's section (use when no gaps remain)")
    ap.add_argument("--list", action="store_true", dest="list_only",
                    help="print the current queue and exit")
    args = ap.parse_args()

    anchor = args.lab or "."
    root = find_project_root(anchor)
    todo_path = os.path.join(root, "docs", "labs", "TODO.md")
    sections = parse_todo(todo_path)
    for s in sections:
        s.setdefault("title", lab_title(os.path.join(root, "docs", "labs", s["lab"])))

    if args.list_only:
        if not sections:
            print("No open lab gaps recorded.")
            return
        for s in sorted(sections, key=lambda x: x["score"]):
            print(f"{s['score']:>3}/100  {s['band']:<18} {s['lab']:<30} "
                  f"{open_items(s['body'])} open  ({s['top']})")
        return

    if not args.lab:
        raise SystemExit("ERROR: a lab path is required unless --list is used")

    key = lab_key(args.lab)
    existing = next((s for s in sections if s["lab"] == key), None)

    if args.clear:
        if existing:
            sections.remove(existing)
            with open(todo_path, "w", encoding="utf-8") as f:
                f.write(render(sections))
            print(f"Removed {key} from docs/labs/TODO.md — no gaps remain.")
        else:
            print(f"{key} had no section in docs/labs/TODO.md; nothing to clear.")
        return

    if args.score is None or not args.band or not args.gaps:
        raise SystemExit("ERROR: --score, --band and --gaps are required")
    if not os.path.isfile(args.gaps):
        raise SystemExit(f"ERROR: no such gaps file: {args.gaps}")

    with open(args.gaps, encoding="utf-8") as f:
        body = f.read().strip("\n")
    if not re.search(r"^\s*-\s*\[[ xX]\]", body, re.MULTILINE):
        raise SystemExit("ERROR: the gaps file has no '- [ ] **Gap** ...' checkbox items")

    if existing:
        body = reapply_completed(body, completed_labels(existing["body"]))
        sections.remove(existing)

    if open_items(body) == 0:
        if existing:
            with open(todo_path, "w", encoding="utf-8") as f:
                f.write(render(sections))
            print(f"All gaps closed for {key}; section removed from docs/labs/TODO.md.")
        else:
            print(f"No open gaps for {key}; nothing written.")
        return

    sections.append({
        "lab": key,
        "title": args.title or lab_title(args.lab),
        "score": args.score,
        "band": args.band,
        "updated": datetime.date.today().isoformat(),
        "top": args.top_gap or first_gap_label(body),
        "body": body,
    })

    os.makedirs(os.path.dirname(todo_path), exist_ok=True)
    with open(todo_path, "w", encoding="utf-8") as f:
        f.write(render(sections))
    print(f"docs/labs/TODO.md updated: {key} ({args.score}/100, "
          f"{open_items(body)} open items, {len(sections)} labs in queue)")


if __name__ == "__main__":
    main()
