site_name: Beginning Electronics
site_description: 'Given a $15 breadboard kit, use AI to generate lessons. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/beginning-electronics'
repo_url: 'https://github.com/dmccreary/beginning-electronics'

nav:
  - Home: index.md
  - Lessons:
    - Introduction: lessons/index.md
    - Components: lessons/components.md
    - Breadboard: lessons/breadboard.md
    - LED Circuit: lessons/led-circuit.md
    - Buttons: lessons/11-buttons.md
    - Buttons AND: lessons/12-and-buttons.md
    - Buttons OR: lessons/13-or-buttons.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX