site_name: Beginning Electronics
site_description: 'Given a $15 breadboard kit, use AI to generate lessons. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/beginning-electronics'
repo_url: 'https://github.com/dmccreary/beginning-electronics'

nav:
  - Home: index.md
  - Getting Started:
    - Introduction: setup/index.md
    - Kit Components: setup/05-kit-components.md
    - Purchasing Kits: setup/breadboard-kits.md
    - Generating Lessons: setup/generating-lessons.md
  - Lessons:
    - Introduction: lessons/index.md
    - Components: lessons/components.md
    - Breadboard: lessons/08-breadboard.md
    - Power: lessons/09-power.md
    - LED Circuit: lessons/10-led-circuit.md
    - Buttons: lessons/11-buttons.md
    - Buttons AND: lessons/12-and-buttons.md
    - Buttons OR: lessons/13-or-buttons.md
    - RC Circuit: lessons/80-rc-circuit.md
  - Simulations:
    - Introduction: sims/index.md
    - Breadboard: sims/breadboard.md
    - LEDs: sims/led.md
    - Push Buttons: sims/push-buttons.md
    - Resistors: sims/resistors.md
    - 555 Timer: sims/timer.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX